#!/bin/sh

set -e

setcap CAP_NET_ADMIN+eip /usr/bin/webxd 2>/dev/null || true

if [ -z "$2" ]; then
    printf "\n"
    printf "\033[32;1mWebX has been installed successfully!\033[0m\n"
    printf "System-wide configuration file is located at /etc/webx/config.toml\n"
    printf "You can start WebX as specified user by running \`systemctl start webx@{username}\` as root\n"
    printf "User specified after @, along with root, will have access to WebX CLI (command 'webx-cli')\n"
    printf "\n"
else
    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet "webx@*" 2>/dev/null; then
        printf "\n\033[33;1mNotice:\033[0m WebX systemd unit file updated. Run \`systemctl restart \"webx@*\"\` as root to apply updates.\n\n"
    fi
fi

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi
