#!/usr/bin/env bash

if [ $1 != "remove" ]; then
    exit 0
fi

[[ -d /run/systemd/system ]] && systemctl stop --now webx@\* --all 2> /dev/nulll || /bin/true
find -L /etc/systemd/ -samefile /lib/systemd/system/webx@.service -delete
