#!/bin/sh

set -e

if [ "$1" != "remove" ]; then
    exit 0
fi

if [ -d /run/systemd/system ]; then
    systemctl stop "webx@*" 2>/dev/null || true
fi

find -L /etc/systemd/ -samefile /usr/lib/systemd/system/webx@.service -delete 2>/dev/null || true
