[package]
name = "webx"
description = "A decentralized P2P overlay network with cryptographic IPv6 addressing and packet verification"
repository = "https://github.com/HXM4Tech/WebX"
homepage = "https://github.com/HXM4Tech/WebX"
readme = "README.md"
version = "0.1.0"
authors = ["Krzysztof Stefańczyk <krzys.stefanczyk@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
blake3 = "1.8.6"
caps = "0.5.6"
chrono = { version = "0.4.45", features = [] }
colored = "3.1.1"
getrandom = { version = "0.4.3", features = ["sys_rng"] }
hex = "0.4.3"
k256 = "0.14.0"
kanal = "0.1.1"
lazy_static = "1.5.0"
libc = "0.2.189"
netlink-packet-route = "0.33.0"
rtnetlink = "0.22.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["net", "sync", "time", "macros", "io-util", "rt-multi-thread", "signal"] }
toml = "1.1.4"
tun-tap = "0.1.4"
users = { version = "0.11.0", features = [] }

[profile.release]
opt-level = 3
strip = true
debug = false
codegen-units = 1
lto = true

[package.metadata.deb]
maintainer-scripts = "package-debian/"
assets = [
    ["target/release/webx", "usr/bin/webxd", "755"],
    ["src/cli.py", "usr/bin/webx-cli", "755"],
    ["conf/config.toml", "etc/webx/config.toml", "644"],
    ["conf/webx@.service", "lib/systemd/system/webx@.service", "644"],
    ["README.md", "usr/share/doc/webx/README.md", "644"]
]
depends = "libc6, libgcc-s1, libcap2, findutils, python3"
recommends = "systemd"
section = "network"
license-file = ["LICENSE", "0"]
extended-description = """\
WebX is a decentralized P2P overlay network featuring cryptographic IPv6
addressing and packet verification.

Recommended packages:
 * systemd: Needed to run the WebX daemon (webxd) as a system service.\
"""
