# WebX daemon configuration file
# Note that this file can be overriden by ~/.config/webx/webx.conf in the user's home directory

# Disable the server by setting this to false if you want to connect only as a client
# this is useful when you are behind a NAT and you can't open the port
server_enabled = true

# The port on which the server will listen
server_port = 4760

# You can add peers, that the WebX daemon will connect to as client on startup
# The format is "address:port"
# Example:
#  initial_peers = ["192.168.1.20", "10.100.1.30:1234", "example.com:1234"]
initial_peers = []
