# WebX daemon configuration file
# Note that this file can be overriden by ~/.webx/config.toml in the user's home directory

# The address and port to bind the UDP socket to.
bind_addr = "[::]:4760"

# You can add peers, that the WebX daemon will connect to as client on startup
# The format is "address:port"
# Example:
#  initial_peers = ["192.168.1.20", "10.100.1.30:1234", "example.com:1234"]
initial_peers = []
