#!/bin/sh

setcap CAP_NET_ADMIN+eip /usr/bin/webxd
systemctl daemon-reload

if [ -z "$2" ]; then
    printf "WebX has been installed successfully!\n"
    printf "System-wide configuration file is located at /etc/webx/config.toml\n"
    printf "You can start WebX by running 'systemctl start webx@{user}' as root\n"
    printf "User provided as argument will have access to WebX CLI with command 'webx-cli' along with root\n"
else
    systemctl restart webx@\* --all
fi
